version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
  parse:
    image: 'parseplatform/parse-server:latest'
    ports:
      - '127.0.0.1:1337:1337'
    environment:
      - PARSE_SERVER_APPLICATION_ID=${PARSE_APP_ID}
      - PARSE_SERVER_MASTER_KEY=${PARSE_MASTER_KEY}
      - PARSE_APP_NAME=${PARSE_APP_NAME}
      - PARSE_SERVER_CLOUD=/parse-server/cloud/main.js
      - PARSE_SERVER_DATABASE_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}
      - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
      - PARSE_SERVER_LIVE_QUERY=${PARSE_SERVER_LIVE_QUERY}
    volumes:
      - 'parse_data:/parse-server/config'
      - './cloud/:/parse-server/cloud'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'parseplatform/parse-dashboard:latest'
    ports:
      - '127.0.0.1:80:4040'
    depends_on:
      - parse
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
    volumes:
      - './config.json:/src/Parse-Dashboard/parse-dashboard-config.json'
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local